### ISSUE TITLE
info panel empty + slight visual bug

### ISSUE THREAD

**Issue by BirdyOz** [unknownuser88/PackagesUI#2]
Hi there.

I was hugely excited to find your plugin as I've been desperate for a way to better manage my ST3 packages and toggle them on/off as needed.

Unfortunately, the info panel is not working for me ..... whilst the panel launches, it is blank.  See screencapture: https://db.tt/2swdV4JNAU

I wondered whether this was theme related, but I have tried a range of themes without success.  From your screencaps, I suspect we are both using the  Boxy theme.

Also, you will notice a slight visual bug at the top of the panel, where the 'refresh' menu item is overlapping the 'banner'.  I'm not concerned by this second issue, but thought I would raise it with you.

System info:
- MacOS Sierra 10.12.5
- Sublime Text 3 Build 3216 
- PackagesUI 1.0.1
- Theme: Boxy Tomorrow

**Comment by unknownuser88** [comment]
in version 1.0.2 visual bug should be fixed but for info panel I need little more info 
please check sublime console for any errors of PackagesUI plugin

**Comment by BirdyOz** [comment]
Thankyou for your prompt response.

I upgraded to 1.0.2 which has fixed the rendering bug, thanks.  The 'empty info' bug still remains.

I've turned on console logging and captured the following.  I can't see any obvious errors.  

```
>>> sublime.log_commands(True)
command: packages_ui
[Packages UI] render
command: toggle_info_panel
command: show_panel {"panel": "console", "toggle": true}
```

Is there anything else I can look to?  Any possible conflicts with other plugins? Has it been tested on Mac?

**Comment by unknownuser88** [comment]
I didn't test it on mac only linux & win10 
I'm going to debug plugin on mac as soon as posible
I think it's not conflict with other plugins maybe the plugins folder structure different on mac and it unable to get info

**Comment by BirdyOz** [comment]
Thansk heaps.  Let me know if you need any help on the Mac testing side.  I don't claim to have very strong developer skills, but I might be able to do debugging and end-user testing

**Comment by unknownuser88** [comment]
thank you very much for your help

please check some things on mac os

1. open sublime text console and paste `sublime.installed_packages_path()` it should return path send it to me and open it in file browser there should be packages with extentions .sublime-package (ex. ColorPicker.sublime-package ) try to open it and check if there package-metadata.json file in it

2. open sublime text console and paste `sublime.packages_path()` it also should return folder path but in this path should be pacakge folders open it and check for package-metadata.json file, send this path to me

3. in your sublime text menu open Preferences -> Browse Packages and also send path to me

I think the reason why info panel empty the plugin unable to find package-metadata.json file to read from it

**Comment by BirdyOz** [comment]
Hi David.

Sorry for my slow reply.  It has been a long weekend here in Australia and
I have been away camping.

See my responses to your q’s in bold, below.
Thanks again, Greg

Cheers, Greg

……………………………………..

Greg Bird

   - Mobile: 0424 196 530
   - Email: greg.bird.oz@gmail.com
   - Twitter: http://twitter.com/BirdyOz
   - LinkedIn: http://www.linkedin.com/in/BirdyOz
   - YouTube: http://www.youtube.com/BirdyOz

eLearning Consultant | Instructional Designer | eLearning Content
Development | Strategy and Implementation | Moodle specialist |
Professional Development | Teacher | Screen recording | Web and Multimedia
Developer | eLearning Systems Administrator | Systems integration
……………………………………..

On 9 June 2017 at 6:24:00 pm, David (notifications@github.com) wrote:

thank you very much for your help

please check some things on mac os

   1.

   open sublime text console and paste sublime.installed_packages_path() it
   should return path send it to me and open it in file browser there should
   be packages with extentions .sublime-package (ex.
   ColorPicker.sublime-package ) try to open it and check if there
   package-metadata.json file in it


*>>> sublime.installed_packages_path()'/Users/BirdyOz/Library/Application
Support/Sublime Text 3/Installed Packages’*

*There is no 'package-metadata.json’ in this directory. *




   1.


   open sublime text console and paste sublime.packages_path() it also
   should return folder path but in this path should be pacakge folders open
   it and check for package-metadata.json file, send this path to me


*>>> sublime.packages_path()'/Users/BirdyOz/Library/Application
Support/Sublime Text 3/Packages’*

*Similar to above, there is no 'package-metadata.json’ file in this
directory.*


*There is, however, 'package-metadata.json’ files in some, but not all of
the packages subdirectories …..*




   1.


   in your sublime text menu open Preferences -> Browse Packages and also
   send path to me

*This is the same directory as above, i.e.*

*'/Users/BirdyOz/Library/Application Support/Sublime Text 3/Packages’*



I think the reason why info panel empty the plugin unable to find
package-metadata.json file to read from it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/unknownuser88/PackagesUI/issues/2#issuecomment-307327856>,
or mute the thread
